### ISSUE TITLE
application/mathml+xml correct in media types?

### ISSUE THREAD

**Issue by NSoiffer** [w3c/mathml-docs#38]
I'm not up to date on media types, so this may be a stupid question...

In https://w3c.github.io/mathml-docs/mathml-media-types/#media-type-choosing, the media types are all `application/mathml... +xml`. Is `+html` allowed? If so, seems like that should be mentioned.

**Comment by NSoiffer** [comment]
I just clicked through to RFC3023 and see that only has `Application/mathml+xml`. This doc is 2001. Is there a better/more up-to-date reference?

**Comment by davidcarlisle** [comment]
3023 is just the general `foo+xml` scheme, it doesn't get updated for specific instances of xml media types.  The currently registered up to date reference for the 3 mathml types is the appendix in MathML3 that this would replace.  There is no corresponding `+html` scheme, you'd use `text/html` to get html parsed  MathML

**Comment by polx** [comment]
Right. The +xml suffix is defined by RFC 3023 (and indeed MathML's generic content-type as well).
RFC3023 is important when registering a +xml type because it defines a few aspects of the transmission (including the somewhat difficult charset family of parameters).

The current list of all registered media types is displayed at the IANA: https://www.iana.org/assignments/media-types/media-types.xhtml
It is regularly updated.

That list would be updated with a different URL once we publish an independent recommendation with the MathML-media-types.

**Comment by NSoiffer** [comment]
Thanks for the corrections -- I guess I already knew that...

One of my concerns with RFC3023 is that it says 
> [MathML](https://www.rfc-editor.org/rfc/rfc3023#ref-MathML) documents are XML documents whose content describes
   mathematical information, as defined by [MathML].  As a format based
   on XML, MathML documents SHOULD use the '+xml' suffix convention in
   their MIME content-type identifier.  However, no content type has yet
   been registered for MathML and so this media type should not be used
   until such registration has been completed.

I think it would be a good idea to include the IANA ref/link so that people can easily find that the registration has been completed.

**Comment by davidcarlisle** [comment]
@NSoiffer  hmm RFC can't be changed, only errata or a new one obsoleting the existing one.

Turns out 3023 has both

https://www.rfc-editor.org/errata_search.php?rfc=3023

says 3023 is obsoleted by  [7303](https://www.rfc-editor.org/info/rfc7303) that removes mention of mathml as an example +xml  type but it has status "proposed" although dated back in 2014. Wikipedia seems to take it as authoritative though https://en.wikipedia.org/wiki/XML_and_MIME
 perhaps we should replace the 3023 reference with 7303, @polx ?

**Comment by polx** [comment]
We shouldn't expect an RFC to mention MathML. It will be outdated at some point.
The [list](https://www.iana.org/assignments/media-types/media-types.xhtml) is the source to mention MathML and to be updated.

As for the evolution of 3023, this is discussed currently, but with respect to the possibility of registering new suffix types (json was suggested, several suffixes were discussed). Do we have a reason to try to bring back MathML? I think rather no.

**Comment by davidcarlisle** [comment]
@NSoiffer, as @polx says +xml RFC  not mentioning MathML is good I think. It was only mentioned in 3023 as a speculative example as a there were no actual +xml vocabularies at the time, and as shown here having examples in the generic rfc that can't be changed just causes issues down the line.

**Comment by polx** [comment]
It was discussed today and decided:
- to add a reference to the revisions of RFC3023 everytime we reference RFC3023 (at least the [latest](https://www.rfc-editor.org/rfc/rfc7303))
- to make the "list of media types" a reference as well (maybe with a "last checked" comment)

**Comment by polx** [comment]
I have now:

- thinned the set of unused references in the header
- reference the registration process and the list of media-types as bib entries
- converted references from rfc3023 to rfc7303 (which obsoletes it)

I believe that this addresses all issues mentioned here.
